FROM postgres:13

# Copy initialization scripts
COPY postgres/init-databases.sh /docker-entrypoint-initdb.d/
COPY postgres/scripts/db-v3.sql /docker-entrypoint-initdb.d/

# Set environment variables
ENV POSTGRES_USER=program
ENV POSTGRES_PASSWORD=test
ENV POSTGRES_DB=postgres

# Expose PostgreSQL port
EXPOSE 5432
